---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../projects/self
  - ../../projects/infra
  - ../../.argocd/bootstrap
  # - ./infra.yaml
  # - ./apps.yaml

patches:
  - path: patches/argocd.app.yaml
    target:
      kind: Application
      group: argoproj.io
      version: v1alpha1
      name: argocd
      namespace: argocd
