---
global:
  domain: argo.dev.inexistent.xyz

configs:
  cm:
    exec.enabled: true
  secret:
    createSecret: true

server:
  extensions:
    enabled: true
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.5/extension.tar
