---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appmesh-system
resources:
  - ../../base

helmCharts:
  - name: appmesh-controller
    repo: https://aws.github.io/eks-charts
    version: 1.13.1
    namespace: appmesh-system
    releaseName: appmesh-controller
    valuesFile: ../../base/appmesh-controller.helm.values.yaml
    additionalValuesFiles:
      - appmesh-controller.helm.values.yaml
