---
- op: add
  path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  value: "" # TODO

## comma-separated list of hostnames
- op: add
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: argocd.dev.inexistent.xyz # TODO

- op: add
  path: /spec/tls
  value:
    - hosts:
        - argocd.dev.inexistent.xyz # TODO

- op: add
  path: /spec/rules
  value:
    - host: argocd.dev.inexistent.xyz # TODO
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
