---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-gateway
  namespace: observability
spec:
  mode: deployment
  serviceAccount: otel-collector
  autoscaler:
    minReplicas: 2
    maxReplicas: 20
  config:
    extensions:
      health_check: {}

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    receivers:
      zipkin: {}

      # otlp:
      #   protocols:
      #     grpc:
      #     http:

      # jaeger:
      #   protocols:
      #     grpc:
      #     thrift_binary:
      #     thrift_compact:
      #     thrift_http:

    exporters:
      debug: {}

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [zipkin]
          processors: [memory_limiter, batch]
          exporters: [debug]
