---
- op: add
  path: /spec/target/template/data
  value:
    ## TODO: add account ID and region containing ECR images
    .dockerconfigjson: |
      {
        "auths": {
          "<acct-id>.dkr.ecr.<region>.amazonaws.com": {
            "username": "AWS",
            "password": "{{ .password }}",
            "auth": "{{ printf "%s:%s" "AWS" .password | b64enc }}"
          }
        }
      }
