---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - ../../base

# https://github.com/kubernetes-sigs/kustomize/issues/4658#issuecomment-1951406289
helmCharts:
  - repo: https://charts.jetstack.io
    namespace: cert-manager
    name: cert-manager
    version: v1.16.0
    releaseName: cert-manager
    valuesFile: ../../base/cert-manager.helm.values.yaml
    additionalValuesFiles:
      - cert-manager.helm.values.yaml
