# https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml
---
fullnameOverride: karpenter

serviceAccount:
  create: true
  name: karpenter
  annotations: {}

controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
#
# settings:
#   clusterName: example
#   interruptionQueue: example
