---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [missingkey=error]
  template:
    metadata:
      name: "{{.name}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      # annotations:
      #   argocd.argoproj.io/sync-wave: "{{.wave}}"
    spec:
      project: infra
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        targetRevision: main
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
