---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../../base

patches:
  - path: ../../shared-patches/all/default.ecr-auth-token.yaml
    target:
      kind: ECRAuthorizationToken
      group: generators.external-secrets.io
      version: v1alpha1
      name: aws-ecr-token
      namespace: argocd

  - path: ../../shared-patches/all/aws-ecr-token-dockerconfig.externalsecret.yaml
    target:
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
      name: aws-ecr-token-dockerconfig
      namespace: argocd

  - path: ../../shared-patches/all/aws-ecr-token-oci.externalsecret.yaml
    target:
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
      name: aws-ecr-token-oci
      namespace: argocd
