---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

# https://github.com/kubernetes-sigs/kustomize/issues/4658#issuecomment-1951406289
helmCharts:
  - name: karpenter-crd
    repo: oci://public.ecr.aws/karpenter
    version: 0.37.0
    namespace: kube-system
    releaseName: karpenter-crd

  - name: karpenter
    repo: oci://public.ecr.aws/karpenter
    includeCRDs: false
    version: 0.37.0
    namespace: kube-system
    releaseName: karpenter
    valuesFile: ../../base/karpenter.helm.values.yaml
    additionalValuesFiles:
      - karpenter.helm.values.yaml
