# https://github.com/argoproj/argo-cd/issues/16623#issuecomment-2176566772
# workaround for a kustomize limitation:
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/helmcharts/#long-term-support
# kustomize doesn't support inflating helm charts from private OCI repositories
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ecr-token-dockerconfig
  namespace: argocd
spec:
  refreshInterval: 30m
  target:
    name: aws-ecr-token-dockerconfig
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: aws-ecr-token
