---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-ecr-token-oci
  namespace: argocd
spec:
  refreshInterval: 30m
  target:
    name: aws-ecr-token-oci
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: helm
        name: helm ## TODO: example
        enableOCI: "true"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: aws-ecr-token
