---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - ../../base

# https://github.com/kubernetes-sigs/kustomize/issues/4658#issuecomment-1951406289
helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.14.5
    namespace: external-dns
    releaseName: external-dns
    valuesFile: ../../base/external-dns.helm.values.yaml
    additionalValuesFiles:
      - external-dns.helm.values.yaml
