---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/argocd.tgb.yaml
    target:
      kind: TargetGroupBinding
      group: eks.amazonaws.com
      version: v1
      name: argocd
      namespace: argocd

  - path: patches/argocd-grpc.tgb.yaml
    target:
      kind: TargetGroupBinding
      group: eks.amazonaws.com
      version: v1
      name: argocd-grpc
      namespace: argocd
