---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argocd
  namespace: argocd
spec:
  serviceRef:
    name: argocd-server
    port: 443
  networking:
    ingress:
      - from:
          - securityGroup:
              groupID: ""
        ports:
          - port: 8080
            protocol: TCP
