---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/secrets-manager.clustersecretstore.yaml
    target:
      kind: ClusterSecretStore
      group: external-secrets.io
      version: v1beta1
      name: aws-secrets-manager
