---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ../../base

# https://github.com/kubernetes-sigs/kustomize/issues/4658#issuecomment-1951406289
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server
    version: 3.12.1
    namespace: kube-system
    releaseName: metrics-server
    valuesFile: ../../base/metrics-server.helm.values.yaml
    additionalValuesFiles:
      - metrics-server.helm.values.yaml
